backend:
  name: git-gateway
  repo: kiliw/gatsby-netlify-cms-typescript-template

media_folder: "static/img"
public_folder: "/img"
publish_mode: "editorial_workflow"

collections:
  - name: "home"
    label: "MainPage"
    delete: false
    files:
      - file: "src/content/home/home.json"
        name: "home"
        label: "Home"
        format: "json"
        identifier_field: "id"
        fields:
          - name: "id"
            widget: "hidden"
            default: "home"

          - name: "title"
            widget: "string"
          - name: "introduction"
            widget: "markdown"
